In [11]:
import pandas as pd

df_src = pd.read_csv("under_cloud_zzggll20240808-1723092527639.csv",low_memory=False)
df_sroted = df_src.sort_values(by=['DEVICE_ID', 'UPLOADTIME'], ascending=[True,False])
df_latest = df_sroted.drop_duplicates(subset='DEVICE_ID', keep='first')
df_cloud = pd.read_csv("cloud_zzggll20240808.csv",low_memory=False)
df_latest = df_latest[~df_latest['DEVICE_ID'].isin(df_cloud['device_id'])]
df_latest.describe()

,VERSION_UP,DEVICE_ID,DEVICE_TYPE_CODE,REMOTEMODE_CODE,VOICETYPE_CODE,OS_TYPE_CODE,RESERVER,OBJECT_STATUS_CODE,OBJECT_VERSION_NUMBER,CREATED_BY,...,LAST_UPDATED_BY,LAST_UPDATED_DATE,SAVETIME,RECEIVETIME,FIELDDTU,PHONENO_COUNT,PHONENO2,PHONENO3,PHONENO4,PHONENO5
count,1064.0,1064.000000,1064.0,1064.000000,1064.0,1064.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.064000e+03,1064.0,6.910000e+02,2.710000e+02,1.020000e+02,4.500000e+01
mean,20130131.0,354239.383459,6.0,1.987782,3.0,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.790109e+07,5.0,1.456003e+10,1.383418e+10,1.273733e+10,1.370674e+10
std,0.0,20131.846033,0.0,0.361404,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6.424119e+05,0.0,9.016973e+09,1.336907e+10,9.244718e+09,6.294114e+09
min,20130131.0,0.000000,6.0,0.000000,3.0,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.263005e+07,5.0,9.621210e+05,5.081639e+07,1.000000e+00,6.442127e+07
25%,20130131.0,349056.750000,6.0,2.000000,3.0,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.800220e+07,5.0,1.361397e+10,1.350195e+10,1.337214e+10,1.352431e+10
50%,20130131.0,358914.500000,6.0,2.000000,3.0,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.800327e+07,5.0,1.391853e+10,1.390592e+10,1.364920e+10,1.373423e+10
75%,20130131.0,364239.500000,6.0,2.000000,3.0,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.800418e+07,5.0,1.816875e+10,1.755085e+10,1.588100e+10,1.570521e+10
max,20130131.0,451402.000000,6.0,10.000000,3.0,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.900000e+07,5.0,1.391881e+11,1.891450e+11,7.608834e+10,4.118273e+10